# 04 — Baseline RF/XGB sobre features combinados (EPIC 4)

**Avance 3 — Baseline · CRISP-ML(Q) fase 3 Modeling**

Este notebook entrena dos modelos tabulares (Random Forest y XGBoost) sobre el vector de features del EPIC 3 (AlphaEarth 64-dim + indices espectrales + estadisticas temporales + SRTM + ERA5) y documenta su desempeno contra el umbral minimo del Avance 3.

| Seccion | Contenido | US |
|---------|-----------|-----|
| 1 | Setup y carga del dataset | US-019 |
| 2 | Justificacion del algoritmo (40 pts) | US-019 |
| 3 | Importancia de features nativa | US-020 |
| 4 | Analisis SHAP | US-020 |
| 5 | Conclusiones de feature engineering | US-020 |
| 5b | Curvas de aprendizaje y validacion | US-021 |
| 6 | Desempeno minimo vs umbral 0.60 (10 pts) | US-019 |
| 7 | Comparativa AlphaEarth vs Sentinel-2 crudo | US-022 |
| 8 | Discusion y decisiones para EPIC 5 | US-022 |

## 1. Setup y carga del dataset

El dataset de entrada es el subset PASTIS-R a nivel parcela generado en el EPIC 3 (US-018): 85.951 parcelas x 187 features espectro-temporales. Las etiquetas son las 20 clases de cultivo de PASTIS-R (se descartan las clases de fondo).

In [1]:
# Parametros papermill (celda con tag 'parameters'; sobreescribibles
# en CI con valores reducidos via `papermill -p`).
FEATURES_PATH = 'data/test_fixtures/feature_selection_parcels_subset.parquet'
MAX_SAMPLES = 0  # 0 = dataset completo; >0 = submuestreo estratificado
TUNE = True
F1_THRESHOLD = 0.60

In [2]:
# Parameters
MAX_SAMPLES = 3000
TUNE = False

In [3]:
import warnings

import matplotlib

matplotlib.use('Agg')  # backend headless para papermill/CI
import matplotlib.pyplot as plt
import polars as pl

warnings.filterwarnings('ignore')

In [4]:
from ml.train.baseline import _load_baseline_dataset, _prepare_dataframe

df_raw = _load_baseline_dataset(FEATURES_PATH)
df = _prepare_dataframe(df_raw)
print(f'Parcelas: {df.height:,}  |  Columnas: {df.width}')
df.head()

Parcelas: 85,951  |  Columnas: 192

shape: (5, 192)
┌───────────┬──────┬───────────┬──────────┬───┬─────────────┬──────────┬──────┬──────────┐
│ parcel_id ┆ year ┆ NDVI_mean ┆ NDVI_std ┆ … ┆ instance_id ┆ class_id ┆ fold ┆ n_pixels │
│ ---       ┆ ---  ┆ ---       ┆ ---      ┆   ┆ ---         ┆ ---      ┆ ---  ┆ ---      │
│ str       ┆ i64  ┆ f64       ┆ f64      ┆   ┆ i64         ┆ i64      ┆ i64  ┆ i64      │
╞═══════════╪══════╪═══════════╪══════════╪═══╪═════════════╪══════════╪══════╪══════════╡
│ 10000_1   ┆ 2018 ┆ 0.451583  ┆ 0.425313 ┆ … ┆ 1           ┆ 2        ┆ 1    ┆ 101      │
│ 10000_2   ┆ 2018 ┆ 0.499859  ┆ 0.613426 ┆ … ┆ 2           ┆ 2        ┆ 1    ┆ 146      │
│ 10000_3   ┆ 2018 ┆ 0.334038  ┆ 0.27952  ┆ … ┆ 3           ┆ 12       ┆ 1    ┆ 222      │
│ 10000_5   ┆ 2018 ┆ 0.38247   ┆ 0.285132 ┆ … ┆ 5           ┆ 2        ┆ 1    ┆ 161      │
│ 10000_7   ┆ 2018 ┆ 0.31712   ┆ 0.238965 ┆ … ┆ 7           ┆ 13       ┆ 1    ┆ 154      │
└───────────┴──────┴───────────┴──────────┴───┴─────────────┴──────────┴──────┴──────────┘

In [5]:
# Distribucion de clases — PASTIS-R tiene desbalance fuerte.
class_counts = (
    df.group_by('class_id').len().sort('len', descending=True)
)
class_counts

shape: (18, 2)
┌──────────┬───────┐
│ class_id ┆ len   │
│ ---      ┆ ---   │
│ i64      ┆ u32   │
╞══════════╪═══════╡
│ 1        ┆ 31292 │
│ 3        ┆ 13123 │
│ 8        ┆ 10640 │
│ 2        ┆ 8206  │
│ 14       ┆ 3174  │
│ …        ┆ …     │
│ 6        ┆ 908   │
│ 9        ┆ 871   │
│ 17       ┆ 848   │
│ 18       ┆ 707   │
│ 13       ┆ 551   │
└──────────┴───────┘

## 2. Justificacion del algoritmo

Se eligen **Random Forest** y **XGBoost** como baseline tabular. Cuatro argumentos sustentan la decision:

**(a) AlphaEarth ya codifica la informacion multisensor.** El embedding AlphaEarth Foundations de 64 dimensiones condensa informacion optica, radar y temporal aprendida por un Foundation Model entrenado sobre todo el archivo Sentinel. Sobre una representacion ya rica, un modelo tabular es un baseline suficiente y honesto — no se requiere una arquitectura profunda para establecer el lower bound (cf. Brown et al., 2025, *AlphaEarth Foundations*; EDA US-013).

**(b) RF y XGBoost son interpretables.** Ambos exponen importancia de features nativa (Gini para RF, gain para XGBoost) y son compatibles con SHAP (TreeExplainer exacto). El criterio 'Caracteristicas importantes' del Avance 3 (US-020) depende de esta interpretabilidad — un baseline opaco no permitiria auditar que features aportan (Lundberg & Lee, 2017, *SHAP*).

**(c) Robustez a outliers y a la escala.** Los arboles particionan el espacio por umbrales y no asumen ninguna distribucion de las features; outliers residuales tras la winsorizacion del EPIC 3 no desplazan las fronteras de decision como lo harian en un modelo lineal o en una red sin normalizacion cuidadosa.

**(d) Bajo costo computacional.** El problema (85k x 187, 20 clases) se entrena en minutos. XGBoost usa el GPU local cuando esta disponible y degrada a CPU de forma transparente; RF corre siempre en CPU multinucleo. El baseline es reproducible en la laptop de cualquier integrante del equipo y en CI sin reservar computo cloud, dejando el presupuesto H100 para EPIC 5/6.

## 3. Importancia de features nativa

_Placeholder — completado por US-020 (Feature importance + SHAP)._

## 4. Analisis SHAP

_Placeholder — completado por US-020 (Feature importance + SHAP)._

## 5. Conclusiones de feature engineering

_Placeholder — completado por US-020 (Feature importance + SHAP)._

## 5b. Curvas de aprendizaje y validacion

_Placeholder — completado por US-021 (Curvas de aprendizaje)._

## 6. Desempeno minimo

El Avance 3 fija un umbral de **F1-macro >= 0.60** sobre PASTIS-R. Se entrenan RF y XGBoost con validacion cruzada **espacial** (H3 + KMeans + buffer 1 km, sin leakage entre parcelas vecinas) y se reporta la media CV de cada metrica.

La rubrica evalua que el desempeno este **declarado y justificado**, no que el umbral se supere: si F1-macro < 0.60 se documentan las causas y las decisiones para EPIC 5 en la seccion 6.1.

In [6]:
from ml.train.baseline import train_one_model, tune_baseline

results = {}
for kind in ('rf', 'xgb'):
    if TUNE:
        best_params = tune_baseline(df, model=kind)
        results[kind] = train_one_model(
            df, model=kind, hyperparams=best_params
        )
    else:
        results[kind] = train_one_model(df, model=kind)
    print(f'{kind.upper()}  entrenado.')

2026-05-22 05:04:18 [info     ] spatial_folds_cache_hit        n_folds=5 path=data\test_fixtures\baseline_spatial_folds_n85951_k5_b1_s42.parquet

2026-05-22 05:04:18 [info     ] spatial_cv_start               n_classes=18 n_folds=5

2026-05-22 05:04:18 [info     ] spatial_cv_fold_start          fold=1/5 n_test=23157 n_train=62794

2026-05-22 05:04:18 [info     ] scaler_persisted               n_features=185 n_train=62794 path=C:\Users\arthu\AppData\Local\Temp\tmptg_oq1fh\fold_0_scaler.joblib version=v1

2026-05-22 05:04:30 [info     ] spatial_cv_fold_done           f1_macro=0.3895 fold=1/5

2026-05-22 05:04:30 [info     ] spatial_cv_fold_start          fold=2/5 n_test=8470 n_train=77481

2026-05-22 05:04:30 [info     ] scaler_persisted               n_features=185 n_train=77481 path=C:\Users\arthu\AppData\Local\Temp\tmp6txxm3b3\fold_1_scaler.joblib version=v1

2026-05-22 05:04:47 [info     ] spatial_cv_fold_done           f1_macro=0.3427 fold=2/5

2026-05-22 05:04:47 [info     ] spatial_cv_fold_start          fold=3/5 n_test=22838 n_train=63113

2026-05-22 05:04:47 [info     ] scaler_persisted               n_features=185 n_train=63113 path=C:\Users\arthu\AppData\Local\Temp\tmpq34m0h_b\fold_2_scaler.joblib version=v1

2026-05-22 05:04:59 [info     ] spatial_cv_fold_done           f1_macro=0.3507 fold=3/5

2026-05-22 05:04:59 [info     ] spatial_cv_fold_start          fold=4/5 n_test=20801 n_train=65150

2026-05-22 05:05:00 [info     ] scaler_persisted               n_features=185 n_train=65150 path=C:\Users\arthu\AppData\Local\Temp\tmpg0wnr72j\fold_3_scaler.joblib version=v1

2026-05-22 05:05:13 [info     ] spatial_cv_fold_done           f1_macro=0.166 fold=4/5

2026-05-22 05:05:13 [info     ] spatial_cv_fold_start          fold=5/5 n_test=10685 n_train=75266

2026-05-22 05:05:13 [info     ] scaler_persisted               n_features=185 n_train=75266 path=C:\Users\arthu\AppData\Local\Temp\tmp9qtkz8hc\fold_4_scaler.joblib version=v1

2026-05-22 05:05:29 [info     ] spatial_cv_fold_done           f1_macro=0.2589 fold=5/5

2026-05-22 05:05:46 [info     ] baseline_trained               f1_macro_oof=0.3650014806382986 model=rf n_classes=18 n_features=185 n_samples=85951

RF  entrenado.
2026-05-22 05:05:46 [info     ] spatial_folds_cache_hit        n_folds=5 path=data\test_fixtures\baseline_spatial_folds_n85951_k5_b1_s42.parquet

2026-05-22 05:05:46 [info     ] spatial_cv_start               n_classes=18 n_folds=5

2026-05-22 05:05:46 [info     ] spatial_cv_fold_start          fold=1/5 n_test=23157 n_train=62794

2026-05-22 05:05:46 [info     ] scaler_persisted               n_features=185 n_train=62794 path=C:\Users\arthu\AppData\Local\Temp\tmp1nbqll9b\fold_0_scaler.joblib version=v1

2026-05-22 05:05:47 [info     ] xgb_device_resolved            device=cuda gpu='NVIDIA GeForce RTX 4070 Laptop GPU'

2026-05-22 05:06:52 [info     ] spatial_cv_fold_done           f1_macro=0.4502 fold=1/5

2026-05-22 05:06:52 [info     ] spatial_cv_fold_start          fold=2/5 n_test=8470 n_train=77481

2026-05-22 05:06:53 [info     ] scaler_persisted               n_features=185 n_train=77481 path=C:\Users\arthu\AppData\Local\Temp\tmprd0n29yw\fold_1_scaler.joblib version=v1

2026-05-22 05:06:53 [info     ] xgb_device_resolved            device=cuda gpu='NVIDIA GeForce RTX 4070 Laptop GPU'

2026-05-22 05:08:04 [info     ] spatial_cv_fold_done           f1_macro=0.3772 fold=2/5

2026-05-22 05:08:04 [info     ] spatial_cv_fold_start          fold=3/5 n_test=22838 n_train=63113

2026-05-22 05:08:05 [info     ] scaler_persisted               n_features=185 n_train=63113 path=C:\Users\arthu\AppData\Local\Temp\tmp8fpssjhb\fold_2_scaler.joblib version=v1

2026-05-22 05:08:05 [info     ] xgb_device_resolved            device=cuda gpu='NVIDIA GeForce RTX 4070 Laptop GPU'

2026-05-22 05:09:11 [info     ] spatial_cv_fold_done           f1_macro=0.4059 fold=3/5

2026-05-22 05:09:11 [info     ] spatial_cv_fold_start          fold=4/5 n_test=20801 n_train=65150

2026-05-22 05:09:12 [info     ] scaler_persisted               n_features=185 n_train=65150 path=C:\Users\arthu\AppData\Local\Temp\tmpdk3wpkl_\fold_3_scaler.joblib version=v1

2026-05-22 05:09:12 [info     ] xgb_device_resolved            device=cuda gpu='NVIDIA GeForce RTX 4070 Laptop GPU'

2026-05-22 05:10:15 [info     ] spatial_cv_fold_done           f1_macro=0.2023 fold=4/5

2026-05-22 05:10:15 [info     ] spatial_cv_fold_start          fold=5/5 n_test=10685 n_train=75266

2026-05-22 05:10:15 [info     ] scaler_persisted               n_features=185 n_train=75266 path=C:\Users\arthu\AppData\Local\Temp\tmpk4v7bh0g\fold_4_scaler.joblib version=v1

2026-05-22 05:10:16 [info     ] xgb_device_resolved            device=cuda gpu='NVIDIA GeForce RTX 4070 Laptop GPU'

2026-05-22 05:11:32 [info     ] spatial_cv_fold_done           f1_macro=0.3125 fold=5/5

2026-05-22 05:11:32 [info     ] xgb_device_resolved            device=cuda gpu='NVIDIA GeForce RTX 4070 Laptop GPU'

2026-05-22 05:12:46 [info     ] baseline_trained               f1_macro_oof=0.4094206066320682 model=xgb n_classes=18 n_features=185 n_samples=85951

XGB  entrenado.

In [7]:
# Tabla resumen de las metricas CV-mean por modelo.
summary = pl.DataFrame(
    [
        {
            'modelo': kind.upper(),
            **{m: round(v, 4) for m, v in res.metrics.items()},
        }
        for kind, res in results.items()
    ]
)
summary

shape: (2, 6)
┌────────┬──────────┬─────────────┬────────┬──────────┬─────────────┐
│ modelo ┆ f1_macro ┆ f1_weighted ┆ miou   ┆ accuracy ┆ cohen_kappa │
│ ---    ┆ ---      ┆ ---         ┆ ---    ┆ ---      ┆ ---         │
│ str    ┆ f64      ┆ f64         ┆ f64    ┆ f64      ┆ f64         │
╞════════╪══════════╪═════════════╪════════╪══════════╪═════════════╡
│ RF     ┆ 0.365    ┆ 0.6583      ┆ 0.2699 ┆ 0.6724   ┆ 0.5961      │
│ XGB    ┆ 0.4094   ┆ 0.6917      ┆ 0.3115 ┆ 0.7257   ┆ 0.6546      │
└────────┴──────────┴─────────────┴────────┴──────────┴─────────────┘

In [8]:
# Veredicto vs el umbral del Avance 3.
best_kind = max(results, key=lambda k: results[k].metrics['f1_macro'])
best_f1 = results[best_kind].metrics['f1_macro']
passed = best_f1 >= F1_THRESHOLD
print(f'Mejor modelo: {best_kind.upper()}  |  F1-macro = {best_f1:.4f}')
print(f'Umbral Avance 3: {F1_THRESHOLD:.2f}  |  '
      f'{"ALCANZADO" if passed else "NO alcanzado — ver 6.1"}')

Mejor modelo: XGB  |  F1-macro = 0.4094
Umbral Avance 3: 0.60  |  NO alcanzado — ver 6.1

### 6.1 Causas probables y decisiones para EPIC 5

Si el F1-macro CV-mean queda por debajo de 0.60, las causas probables son:

1. **Granularidad fina de PASTIS-R (20 clases).** Varias clases de cultivo son espectralmente similares; un modelo tabular sobre un embedding anual no captura la firma fenologica que las distingue.
2. **Desbalance de clases.** Pese al balanceo (`class_weight='balanced'` en RF, `sample_weight` inverso a frecuencia en XGBoost), las clases minoritarias aportan pocas parcelas y el F1-macro las penaliza con fuerza.
3. **Limite de un modelo tabular sobre un embedding generico.** AlphaEarth resume el ano en 64 dimensiones; pierde la dinamica temporal intra-anual que un modelo de series temporales si aprovecha.

Decisiones concretas que EPIC 5 incorpora:

- **U-TAE y TSViT** explotan la serie temporal Sentinel-2 completa (no el embedding resumido), capturando la fenologia que separa cultivos similares.
- **Ensamble heterogeneo (EPIC 6)** combina el baseline tabular con los modelos temporales y un VLM, recuperando senal complementaria que ningun modelo aislado captura.

## 7. Comparativa AlphaEarth vs Sentinel-2 crudo

_Placeholder — completado por US-022 (Notebook secuencial + comparativa)._

## 8. Discusion y decisiones para EPIC 5

_Placeholder — completado por US-022 (Notebook secuencial + comparativa)._