# Baseline de clasificación de cultivos — Random Forest y XGBoost

Este notebook responde una pregunta concreta: **¿qué tan lejos llega un modelo tabular sencillo para clasificar cultivos a partir de imágenes satelitales?** Se entrenan dos modelos de árboles (Random Forest y XGBoost) sobre un vector de características que combina el embedding AlphaEarth de 64 dimensiones, índices espectrales, estadísticas temporales, terreno y clima.

El resultado sirve de **punto de referencia**: cualquier modelo más complejo en fases posteriores tendrá que superar estas cifras para justificar su coste.

## Requisitos para ejecución end-to-end

- El subset PASTIS-R a nivel parcela descomprimido en `data/test_fixtures/`.
- Dependencias instaladas via `poetry install --with ml,geo`.

El notebook se ejecuta de principio a fin sin intervención manual; los parámetros (tamaño de muestra, tuning) se ajustan desde la celda de parámetros.

## Contenido

| Sección | Contenido |
|---------|-----------|
| 1 | Carga del conjunto de datos |
| 2 | Por qué Random Forest y XGBoost |
| 3 | Importancia de características |
| 4 | Análisis SHAP |
| 5 | Conclusiones de ingeniería de características |
| 5b | Curvas de aprendizaje y validación |
| 6 | Desempeño del baseline |
| 7 | Comparativa AlphaEarth vs Sentinel-2 crudo |
| 8 | Conclusiones |

## 1. Carga del conjunto de datos

El conjunto de entrada es un subset de PASTIS-R a nivel de parcela: 85.951 parcelas agrícolas con 187 características espectro-temporales cada una. La etiqueta es el tipo de cultivo (20 clases de PASTIS-R; se descartan las clases de fondo).

In [1]:
# Parametros papermill (celda con tag 'parameters'; sobreescribibles
# en CI con valores reducidos via `papermill -p`).
FEATURES_PATH = 'data/test_fixtures/feature_selection_parcels_subset.parquet'
MAX_SAMPLES = 0  # 0 = dataset completo; >0 = submuestreo estratificado
TUNE = True
F1_THRESHOLD = 0.60
# Seccion 7 (US-022) — rutas de los 3 escenarios de la comparativa.
SCENARIO_ALPHAEARTH_PATH = (
    'data/cache/gee/alphaearth_pastis_parcels_2019_85951_enriched.parquet'
)
SCENARIO_S2_RAW_PATH = (
    'data/cache/pastis/s2_raw_parcels_2019_85951.parquet'
)
SCENARIO_COMBINED_PATH = (
    'data/test_fixtures/feature_selection_parcels_subset.parquet'
)
COMPARISON_MAX_SAMPLES = 0  # 0 = todas las parcelas del inner join
COMPARISON_K_FOLDS = 5

In [2]:
# Parameters
MAX_SAMPLES = 4000

In [3]:
import warnings

import matplotlib

matplotlib.use('Agg')  # backend headless para papermill/CI
import matplotlib.pyplot as plt
import polars as pl

warnings.filterwarnings('ignore')

In [4]:
from ml.train.baseline import _load_baseline_dataset, _prepare_dataframe

df_raw = _load_baseline_dataset(FEATURES_PATH)
df = _prepare_dataframe(df_raw)
print(f'Parcelas: {df.height:,}  |  Columnas: {df.width}')
df.head()

Parcelas: 85,951  |  Columnas: 192

shape: (5, 192)
┌───────────┬──────┬───────────┬──────────┬───┬─────────────┬──────────┬──────┬──────────┐
│ parcel_id ┆ year ┆ NDVI_mean ┆ NDVI_std ┆ … ┆ instance_id ┆ class_id ┆ fold ┆ n_pixels │
│ ---       ┆ ---  ┆ ---       ┆ ---      ┆   ┆ ---         ┆ ---      ┆ ---  ┆ ---      │
│ str       ┆ i64  ┆ f64       ┆ f64      ┆   ┆ i64         ┆ i64      ┆ i64  ┆ i64      │
╞═══════════╪══════╪═══════════╪══════════╪═══╪═════════════╪══════════╪══════╪══════════╡
│ 10000_1   ┆ 2018 ┆ 0.451583  ┆ 0.425313 ┆ … ┆ 1           ┆ 2        ┆ 1    ┆ 101      │
│ 10000_2   ┆ 2018 ┆ 0.499859  ┆ 0.613426 ┆ … ┆ 2           ┆ 2        ┆ 1    ┆ 146      │
│ 10000_3   ┆ 2018 ┆ 0.334038  ┆ 0.27952  ┆ … ┆ 3           ┆ 12       ┆ 1    ┆ 222      │
│ 10000_5   ┆ 2018 ┆ 0.38247   ┆ 0.285132 ┆ … ┆ 5           ┆ 2        ┆ 1    ┆ 161      │
│ 10000_7   ┆ 2018 ┆ 0.31712   ┆ 0.238965 ┆ … ┆ 7           ┆ 13       ┆ 1    ┆ 154      │
└───────────┴──────┴───────────┴──────────┴───┴─────────────┴──────────┴──────┴──────────┘

In [5]:
# Distribucion de clases — PASTIS-R tiene desbalance fuerte.
class_counts = (
    df.group_by('class_id').len().sort('len', descending=True)
)
class_counts

shape: (18, 2)
┌──────────┬───────┐
│ class_id ┆ len   │
│ ---      ┆ ---   │
│ i64      ┆ u32   │
╞══════════╪═══════╡
│ 1        ┆ 31292 │
│ 3        ┆ 13123 │
│ 8        ┆ 10640 │
│ 2        ┆ 8206  │
│ 14       ┆ 3174  │
│ …        ┆ …     │
│ 6        ┆ 908   │
│ 9        ┆ 871   │
│ 17       ┆ 848   │
│ 18       ┆ 707   │
│ 13       ┆ 551   │
└──────────┴───────┘

## 2. Por qué Random Forest y XGBoost

Se eligen **Random Forest** y **XGBoost** como modelos de referencia. Cuatro razones sustentan la decisión:

**(a) Las imágenes ya vienen resumidas.** El embedding AlphaEarth de 64 dimensiones condensa información óptica, radar y temporal aprendida por un modelo entrenado sobre todo el archivo Sentinel. Sobre una representación ya rica, un modelo de árboles es un punto de referencia suficiente y honesto — no hace falta una red neuronal profunda para establecer el piso de desempeño (cf. Brown et al., 2025, *AlphaEarth Foundations*).

**(b) Son interpretables.** Ambos exponen una medida de importancia de características (Gini para Random Forest, *gain* para XGBoost) y son compatibles con SHAP. Esto permite auditar qué variables explican las predicciones — un modelo opaco no lo permitiría (Lundberg & Lee, 2017, *SHAP*).

**(c) Son robustos a valores atípicos y a la escala.** Los árboles dividen el espacio por umbrales y no asumen ninguna distribución de las variables; los valores atípicos residuales no desplazan las fronteras de decisión como lo harían en un modelo lineal sin normalización cuidadosa.

**(d) Tienen bajo coste computacional.** El problema (85.951 parcelas, 187 variables, 20 clases) se entrena en minutos. XGBoost aprovecha la GPU local cuando está disponible y degrada a CPU de forma transparente; Random Forest corre siempre en CPU multinúcleo. El experimento es reproducible en cualquier laptop.

## 3. Importancia de características

Random Forest y XGBoost exponen una medida de importancia de características sin coste adicional: **Gini** para Random Forest y **gain** para XGBoost. Es el primer diagnóstico de interpretabilidad — barato y directo — antes del análisis SHAP de la sección 4.

Se cargan los modelos ya entrenados desde `artifacts/baseline_{rf,xgb}_v1.joblib`; si los archivos no existen, el notebook entrena los modelos en el momento con los hiperparámetros base.

In [6]:
import joblib
from pathlib import Path

from ml.train.baseline import train_one_model

REPORTS_DIR = Path('reports/baseline')
REPORTS_DIR.mkdir(parents=True, exist_ok=True)
ARTIFACTS = {'rf': Path('artifacts/baseline_rf_v1.joblib'),
             'xgb': Path('artifacts/baseline_xgb_v1.joblib')}

models = {}
for kind, path in ARTIFACTS.items():
    if path.exists():
        payload = joblib.load(path)
        models[kind] = {
            'model': payload['model'],
            'feature_cols': tuple(payload['feature_cols']),
            'source': 'joblib US-019',
        }
    else:
        res = train_one_model(df, model=kind)
        models[kind] = {
            'model': res.model,
            'feature_cols': res.feature_cols,
            'source': 'fallback in-notebook (D8)',
        }
    print(f"{kind.upper()}: {models[kind]['source']}  |  "
          f"{len(models[kind]['feature_cols'])} features")

RF: joblib US-019  |  185 features

XGB: joblib US-019  |  185 features

In [7]:
from ml.eval.interpretability import feature_importance_table

importance = {}
for kind, bundle in models.items():
    table = feature_importance_table(
        bundle['model'], kind, bundle['feature_cols']
    )
    importance[kind] = table
    table.write_csv(REPORTS_DIR / f'feature_importance_{kind}.csv')
importance['rf'].head(10)

2026-05-26 19:56:19 [info     ] feature_importance_table_computed model_kind=rf n_features=185 top_feature=EVI_fft_phase_2

2026-05-26 19:56:19 [info     ] feature_importance_table_computed model_kind=xgb n_features=185 top_feature=MSAVI2_min

shape: (10, 3)
┌──────────────────┬────────────┬──────┐
│ feature          ┆ importance ┆ rank │
│ ---              ┆ ---        ┆ ---  │
│ str              ┆ f64        ┆ i64  │
╞══════════════════╪════════════╪══════╡
│ EVI_fft_phase_2  ┆ 0.031686   ┆ 1    │
│ CCCI_p75         ┆ 0.025438   ┆ 2    │
│ EVI_fft_phase_1  ┆ 0.024245   ┆ 3    │
│ EVI_fft_phase_3  ┆ 0.020832   ┆ 4    │
│ NDCI_p50         ┆ 0.019787   ┆ 5    │
│ MCARI_p95        ┆ 0.019077   ┆ 6    │
│ NDVI_fft_phase_2 ┆ 0.018781   ┆ 7    │
│ NDVI_p50         ┆ 0.018475   ┆ 8    │
│ NDWI_fft_phase_1 ┆ 0.018447   ┆ 9    │
│ NDRE_p50         ┆ 0.018374   ┆ 10   │
└──────────────────┴────────────┴──────┘

In [8]:
# Barplot top-20 de la importancia nativa por modelo.
for kind, table in importance.items():
    top20 = table.head(20)
    fig, ax = plt.subplots(figsize=(8, 6), dpi=200)
    ax.barh(top20['feature'].to_list()[::-1],
            top20['importance'].to_list()[::-1],
            color='#2c7fb8')
    ax.set_xlabel('Importancia (' + ('Gini' if kind == 'rf' else 'gain') + ')')
    ax.set_title(f'Importancia nativa top-20 — {kind.upper()}')
    fig.tight_layout()
    fig.savefig(REPORTS_DIR / f'importance_{kind}_top20.png',
                dpi=200, bbox_inches='tight')
    plt.show()

## 4. Análisis SHAP

La importancia de la sección 3 ordena las características pero no explica *cómo* cada una desplaza la predicción. **SHAP** (Lundberg & Lee, 2017) descompone cada predicción en contribuciones aditivas por característica, con garantías teóricas de consistencia. Para modelos de árboles se usa el algoritmo TreeSHAP, que es exacto.

Detalles de la implementación:

- **Submuestreo**: SHAP se calcula sobre una muestra estratificada de ~3.000 parcelas, no sobre las ~85.000 del conjunto; el coste de TreeSHAP crece con el número de muestras, árboles y profundidad.
- **Multiclase**: PASTIS-R tiene 18-20 clases; la salida multiclase de SHAP se normaliza a un tensor uniforme `(muestras, características, clases)`.
- **Ranking global**: la importancia global es el promedio del valor absoluto de SHAP sobre clases y muestras.

In [9]:
from ml.eval.interpretability import (
    compute_shap_values,
    shap_summary_plot,
    shap_dependence_plots,
    shap_waterfall_plot,
)

SHAP_SAMPLE_SIZE = 3000
shap_results = {}
for kind, bundle in models.items():
    shap_results[kind] = compute_shap_values(
        bundle['model'], df, kind,
        feature_cols=bundle['feature_cols'],
        sample_size=SHAP_SAMPLE_SIZE,
    )
    print(f'{kind.upper()}: tensor SHAP '
          f'{shap_results[kind].values.shape}')

2026-05-26 20:03:56 [info     ] shap_values_computed           model_kind=rf n_classes=18 n_features=185 n_samples=3000 sample_rows=3000

RF: tensor SHAP (3000, 185, 18)

2026-05-26 20:04:01 [info     ] shap_values_computed           model_kind=xgb n_classes=18 n_features=185 n_samples=3000 sample_rows=3000

XGB: tensor SHAP (3000, 185, 18)

In [10]:
# Summary plot (beeswarm/bar) de las top-20 features globales.
for kind, result in shap_results.items():
    fig = shap_summary_plot(result, df, top_n=20)
    fig.savefig(REPORTS_DIR / f'shap_summary_{kind}.png',
                dpi=200, bbox_inches='tight')
    plt.show()

<!-- AUTO-INTERP -->
**Lectura del SHAP summary**: cada punto es una parcela y la posición horizontal indica cuánto desplaza la predicción. Las características están ordenadas por importancia global (media de `|SHAP|`); los colores cálidos representan valores altos del feature y los fríos valores bajos. El ancho horizontal de cada fila revela el rango de impacto que esa característica puede tener, y la separación en clusters de color muestra si el feature tiene un efecto monótono (un solo gradiente) o no monótono (mezcla de cálidos y fríos en el mismo lado). En este baseline tabular, los features que dominan son índices fenológicos (componentes FFT y percentiles de NDVI/EVI/MCARI), no las dimensiones crudas de AlphaEarth — el cruce cuantitativo se documenta en la subsección 4.1.

In [11]:
# Dependence plots de los 5 features mas importantes (RF).
dependence = shap_dependence_plots(
    shap_results['rf'], df, top_features=5
)
for idx, (feature_name, fig) in enumerate(dependence, start=1):
    fig.savefig(
        REPORTS_DIR / f'shap_dependence_{idx}_{feature_name}.png',
        dpi=200, bbox_inches='tight',
    )
    plt.show()

2026-05-26 20:04:03 [info     ] shap_dependence_plots_generated class_idx=0 model_kind=rf n_plots=5

<!-- AUTO-INTERP -->
**Lectura de los dependence plots**: el eje X es el valor del feature y el eje Y el valor SHAP de ese feature para cada parcela. Una pendiente clara indica una relación monótona (más valor del feature → más o menos probabilidad de la clase); la dispersión alta indica interacción con otras variables. En particular, las componentes FFT de NDVI y EVI muestran que el modelo se apoya en la **forma de la curva fenológica anual** (no solo en la media), lo cual es coherente con la biología de los cultivos. El color de los puntos es la variable de interacción automática que SHAP eligió (la feature más correlacionada con la heterogeneidad del efecto).

In [12]:
# Waterfall de una prediccion ejemplo por modelo.
for kind, result in shap_results.items():
    fig = shap_waterfall_plot(result, row=0)
    fig.savefig(REPORTS_DIR / f'shap_waterfall_{kind}.png',
                dpi=200, bbox_inches='tight')
    plt.show()

### 4.1 Dominancia de las dimensiones AlphaEarth

Una pregunta interesante: de las características más influyentes según SHAP, **¿cuántas son dimensiones del embedding AlphaEarth** (`dim_00..dim_63`) frente a índices espectrales, estadísticas temporales o bloques de contexto (radar, terreno, clima)? La respuesta indica cuánto del poder predictivo proviene del embedding satelital frente al resto de las características.

In [13]:
from ml.eval.interpretability import alphaearth_dominance_table

dominance = alphaearth_dominance_table(
    shap_results['rf'].global_importance, top_n=20
)
dominance.write_csv(REPORTS_DIR / 'alphaearth_dominance.csv')
dominance

2026-05-26 20:04:04 [info     ] alphaearth_dominance_computed  dominance_ratio=0.0 n_alphaearth=0 top_n=20

shape: (20, 4)
┌──────┬──────────────────┬────────────────┬────────────┐
│ rank ┆ feature          ┆ family         ┆ importance │
│ ---  ┆ ---              ┆ ---            ┆ ---        │
│ i64  ┆ str              ┆ str            ┆ f64        │
╞══════╪══════════════════╪════════════════╪════════════╡
│ 1    ┆ EVI_fft_phase_2  ┆ spectral_index ┆ 0.004859   │
│ 2    ┆ CCCI_p75         ┆ spectral_index ┆ 0.004565   │
│ 3    ┆ EVI_fft_phase_1  ┆ spectral_index ┆ 0.004053   │
│ 4    ┆ MCARI_p95        ┆ spectral_index ┆ 0.003342   │
│ 5    ┆ NDVI_fft_phase_2 ┆ spectral_index ┆ 0.003161   │
│ …    ┆ …                ┆ …              ┆ …          │
│ 16   ┆ NDRE_p50         ┆ spectral_index ┆ 0.002208   │
│ 17   ┆ GCVI_p50         ┆ spectral_index ┆ 0.002186   │
│ 18   ┆ EVI_p95          ┆ spectral_index ┆ 0.002094   │
│ 19   ┆ MCARI_p25        ┆ spectral_index ┆ 0.002061   │
│ 20   ┆ MCARI_p50        ┆ spectral_index ┆ 0.001976   │
└──────┴──────────────────┴────────────────┴────────────┘

In [14]:
# Conteo por familia y conclusion cuantificada.
family_counts = (
    dominance.group_by('family').len()
    .sort('len', descending=True)
)
n_alphaearth = int(
    dominance.filter(pl.col('family') == 'alphaearth').height
)
top_ae = (
    dominance.filter(pl.col('family') == 'alphaearth')['feature']
    .to_list()[:3]
)
print(f'{n_alphaearth}/20 de las top features SHAP son '
      f'dimensiones AlphaEarth.')
if top_ae:
    print(f'Lideran: ' + ', '.join(top_ae))
family_counts

0/20 de las top features SHAP son dimensiones AlphaEarth.

shape: (1, 2)
┌────────────────┬─────┐
│ family         ┆ len │
│ ---            ┆ --- │
│ str            ┆ u32 │
╞════════════════╪═════╡
│ spectral_index ┆ 20  │
└────────────────┴─────┘

## 5. Conclusiones de ingeniería de características

Esta sección **valida o cuestiona** las decisiones de ingeniería de características de la fase anterior, cruzando los rankings de interpretabilidad de este notebook con los resultados de la selección de variables previa:

- `reports/feature_selection/feature_importance_rf.csv` — importancia exploratoria de la fase de selección.
- `reports/feature_selection/anova_f_scores.csv` — F-scores univariados de la selección.
- `reports/feature_selection/selected_features.json` — el conjunto de variables que se retuvo.

El objetivo es responder tres preguntas: (a) ¿las características más influyentes según SHAP coinciden con las que se seleccionaron?; (b) ¿alguna variable descartada aparece como importante?; (c) ¿la dominancia de AlphaEarth confirma la decisión de usar el embedding como base?

In [15]:
# Cruce de las top SHAP con la seleccion de variables previa.
fs_dir = Path('reports/feature_selection')
top_shap = set(
    shap_results['rf'].global_importance.head(20)['feature'].to_list()
)

fs_importance_path = fs_dir / 'feature_importance_rf.csv'
if fs_importance_path.exists():
    fs_importance = pl.read_csv(fs_importance_path)
    fs_top = set(fs_importance.head(20)['feature'].to_list())
    overlap = top_shap & fs_top
    print(f'Solapamiento top-20 SHAP vs seleccion previa: '
          f'{len(overlap)}/20 caracteristicas.')
    print('Comunes:', sorted(overlap))
    print('Solo en SHAP (revisar FE):', sorted(top_shap - fs_top))
else:
    print('reports/feature_selection/feature_importance_rf.csv '
          'no disponible — se omite el cruce cuantitativo.')

Solapamiento top-20 SHAP vs seleccion previa: 10/20 caracteristicas.
Comunes: ['EVI_fft_phase_1', 'EVI_fft_phase_2', 'EVI_fft_phase_3', 'EVI_p95', 'NDRE_p95', 'NDVI_fft_phase_1', 'NDVI_fft_phase_2', 'NDVI_p50', 'NDWI_fft_phase_1', 'PSRI_p95']
Solo en SHAP (revisar FE): ['CCCI_p75', 'EVI_p25', 'GCVI_p50', 'MCARI_p25', 'MCARI_p50', 'MCARI_p95', 'MSAVI2_min', 'NDCI_p50', 'NDRE_p50', 'NDWI_p50']

### 5.1 Hallazgos

Los numeros concretos del cruce salen de la celda anterior. Los hallazgos que cabe esperar:

1. **Coincidencia entre la importancia simple y SHAP** — las caracteristicas en lo alto del ranking de Gini/gain y las del ranking SHAP coinciden en su mayoria; las discrepancias señalan variables con efectos no lineales o interacciones que SHAP captura mejor que la importancia simple.
2. **Dominancia de AlphaEarth** — la fraccion de dimensiones del embedding (`dim_NN`) entre las 20 mas influyentes (seccion 4.1) indica cuanto del poder predictivo proviene del embedding: si dominan, aporta la mayor parte de la senal; si no, los indices espectrales y las estadisticas estacionales siguen siendo imprescindibles.
3. **Validacion de la seleccion de variables** — si las caracteristicas seleccionadas en la fase previa coinciden con el top de SHAP, la seleccion queda validada; si una variable descartada aparece arriba, es una señal de que conviene revisarla.

### 5.2 Recomendacion para la ingenieria de caracteristicas

Si el cruce de la seccion 5 confirma la seleccion previa, **no se requiere ajuste**: la interpretabilidad del baseline la respalda. Si el cruce cuestiona alguna decision (una variable relevante descartada, o ruido retenido entre las mas influyentes), la recomendacion concreta se documenta para que las fases siguientes la incorporen antes de entrenar modelos mas complejos.

## 5b. Curvas de aprendizaje y validación — diagnóstico de sub/sobreajuste

Esta sección diagnostica si el baseline sub o sobreajusta. Se usan dos herramientas:

- **Curva de aprendizaje**: accuracy de entrenamiento y de validación al crecer el número de muestras de entrenamiento. Un gap grande entrenamiento-validación indica sobreajuste; ambas curvas bajas y juntas, subajuste.
- **Curva de validación**: accuracy frente a un hiperparámetro crítico (`max_depth` para RF, `n_estimators` y `learning_rate` para XGBoost), para localizar la zona de equilibrio.

Toda la evaluación usa el **mismo CV espacial 5-fold** (H3 + KMeans + buffer 1 km) del resto del notebook — los splits se materializan en una lista porque `learning_curve` reusa el `cv` una vez por cada tamaño. El criterio de spatial CV está documentado en `docs/spatial_cv_baseline.md`.

In [16]:
from ml.eval.learning_curves import (
    diagnose_fit,
    plot_learning_curve,
    plot_validation_curve,
)
from ml.train.baseline import _build_cv_splits

# CV espacial materializado (lista de splits posicionales).
cv_splits_5b = _build_cv_splits(
    df, k_folds=5, buffer_km=1.0, random_state=42
)
print(f'CV espacial: {len(cv_splits_5b)} folds materializados')

2026-05-26 20:04:04 [info     ] spatial_folds_cache_hit        n_folds=5 path=data\test_fixtures\baseline_spatial_folds_n85951_k5_b1_s42.parquet

CV espacial: 5 folds materializados

In [17]:
# Curva de aprendizaje RF y XGB (accuracy train/val vs n muestras).
from pathlib import Path

from ml.train.baseline import build_estimator

reports_dir = Path('reports/baseline')
reports_dir.mkdir(parents=True, exist_ok=True)
curve_train_sizes = [0.1, 0.25, 0.4, 0.55, 0.7, 0.85, 1.0]
learning_results = {}
for kind in ('rf', 'xgb'):
    estimator = build_estimator(kind, {})
    lc_result, lc_fig = plot_learning_curve(
        estimator, df, cv_splits_5b,
        train_sizes=curve_train_sizes,
        max_samples=MAX_SAMPLES,
    )
    learning_results[kind] = lc_result
    lc_fig.suptitle(f'Curva de aprendizaje — {kind.upper()}')
    lc_fig.savefig(
        reports_dir / f'learning_curve_{kind}.png',
        dpi=200, bbox_inches='tight',
    )
    plt.show()

2026-05-26 20:04:04 [info     ] learning_curve_subsampled      max_samples=4000 n_kept=4000 n_original=85951

2026-05-26 20:04:04 [info     ] learning_curve_start           n_features=185 n_folds=5 n_samples=4000 n_train_sizes=7 scoring=accuracy

2026-05-26 20:04:50 [info     ] learning_curve_done            train_acc_max=1.0 val_acc_max=0.6864

2026-05-26 20:04:50 [info     ] xgb_device_resolved            device=cuda gpu='NVIDIA GeForce RTX 4070 Laptop GPU'

2026-05-26 20:04:51 [info     ] learning_curve_subsampled      max_samples=4000 n_kept=4000 n_original=85951

2026-05-26 20:04:51 [info     ] learning_curve_start           n_features=185 n_folds=5 n_samples=4000 n_train_sizes=7 scoring=accuracy

2026-05-26 20:06:12 [info     ] learning_curve_done            train_acc_max=1.0 val_acc_max=0.6903

<!-- AUTO-INTERP -->
**Lectura de las curvas de aprendizaje**: la curva azul (entrenamiento) **se mantiene en 1.0** prácticamente desde el primer tamaño de muestra — el modelo memoriza el entrenamiento sin esfuerzo. La curva naranja (validación) **converge alrededor de 0.68** con una banda ±std amplia. El gap entrenamiento-validación supera 0.30, muy por encima del umbral 0.10 de la regla `diagnose_fit`. Veredicto: **sobreajuste estructural**, no por falta de regularización sino por la combinación de muchas características (~190) sobre un dataset relativamente pequeño con 20 clases desbalanceadas. Subir el número de muestras no cierra el gap — la accuracy de validación se estabiliza, no sigue creciendo. La celda siguiente lo confirma con `diagnose_fit` cuantitativo.

In [18]:
# Diagnostico explicito de sub/sobreajuste por modelo.
for kind, lc_result in learning_results.items():
    diag = diagnose_fit(lc_result)
    print(f'{kind.upper()}: veredicto={diag.verdict}  '
          f'gap={diag.gap:.4f}  '
          f'train_acc={diag.train_acc_max:.4f}  '
          f'val_acc={diag.val_acc_max:.4f}')
    print(f'  {diag.explanation}')

2026-05-26 20:06:12 [info     ] fit_diagnosed                  gap=0.3136 train_acc_max=1.0 val_acc_max=0.6864 verdict=overfit

RF: veredicto=overfit  gap=0.3136  train_acc=1.0000  val_acc=0.6864
  Sobreajuste: el gap train-val es 0.314 (> 0.10). El modelo memoriza el train (accuracy 1.000) pero generaliza peor en validacion (accuracy 0.686).
2026-05-26 20:06:12 [info     ] fit_diagnosed                  gap=0.3097 train_acc_max=1.0 val_acc_max=0.6903 verdict=overfit

XGB: veredicto=overfit  gap=0.3097  train_acc=1.0000  val_acc=0.6903
  Sobreajuste: el gap train-val es 0.310 (> 0.10). El modelo memoriza el train (accuracy 1.000) pero generaliza peor en validacion (accuracy 0.690).

In [19]:
# Curva de validacion RF — max_depth.
vc_rf, vc_rf_fig = plot_validation_curve(
    build_estimator('rf', {}), df, 'max_depth',
    [5, 10, 15, 20, 30, None], cv_splits_5b,
    max_samples=MAX_SAMPLES,
)
vc_rf_fig.suptitle('Curva de validacion — RF max_depth')
vc_rf_fig.savefig(
    reports_dir / 'validation_curve_rf_max_depth.png',
    dpi=200, bbox_inches='tight',
)
plt.show()

2026-05-26 20:06:12 [info     ] learning_curve_subsampled      max_samples=4000 n_kept=4000 n_original=85951

2026-05-26 20:06:12 [info     ] validation_curve_start         n_folds=5 n_samples=4000 n_values=6 param_name=max_depth scoring=accuracy

2026-05-26 20:07:27 [info     ] validation_curve_done          best_val_acc=0.6893 param_name=max_depth

<!-- AUTO-INTERP -->
**Lectura de la curva de validación (RF, max_depth)**: el entrenamiento satura en 1.0 para cualquier profundidad ≥10, y la validación se mantiene plana en ~0.68 independientemente de `max_depth`. Esto indica que el hiperparámetro **no es la palanca** para mejorar el modelo: cualquier profundidad razonable produce el mismo techo. El cuello de botella no es la capacidad del árbol sino la representación de los datos (resumen anual sin dinámica intra-anual) y la granularidad de las clases (20 categorías finas).

In [20]:
# Curva de validacion XGB — n_estimators.
vc_xgb_ne, vc_xgb_ne_fig = plot_validation_curve(
    build_estimator('xgb', {}), df, 'n_estimators',
    [100, 200, 300, 400, 500], cv_splits_5b,
    max_samples=MAX_SAMPLES,
)
vc_xgb_ne_fig.suptitle('Curva de validacion — XGB n_estimators')
vc_xgb_ne_fig.savefig(
    reports_dir / 'validation_curve_xgb_n_estimators.png',
    dpi=200, bbox_inches='tight',
)
plt.show()

2026-05-26 20:07:27 [info     ] xgb_device_resolved            device=cuda gpu='NVIDIA GeForce RTX 4070 Laptop GPU'

2026-05-26 20:07:28 [info     ] learning_curve_subsampled      max_samples=4000 n_kept=4000 n_original=85951

2026-05-26 20:07:28 [info     ] validation_curve_start         n_folds=5 n_samples=4000 n_values=5 param_name=n_estimators scoring=accuracy

2026-05-26 20:10:55 [info     ] validation_curve_done          best_val_acc=0.6975 param_name=n_estimators

El diagnóstico reporta un veredicto explícito (sobreajuste, subajuste o ajuste adecuado) con la diferencia numérica entre el desempeño en entrenamiento y en validación. Un modelo de árboles sobre estas características tiende a una exactitud modesta: si el veredicto es *ajuste adecuado* pero con exactitud de validación baja, el límite es la **capacidad del modelo**, no el sobreajuste — esto justifica que las fases siguientes incorporen arquitecturas temporales con mayor capacidad.

## 6. Desempeño del baseline

Se define un umbral de referencia de **F1-macro ≥ 0.60** sobre PASTIS-R. Se entrenan Random Forest y XGBoost con validación cruzada **espacial** (celdas hexagonales H3 + agrupamiento KMeans + zona de exclusión de 1 km, para que parcelas vecinas no queden a la vez en entrenamiento y validación) y se reporta el promedio de cada métrica sobre los pliegues.

Lo importante es que el desempeño quede **medido y explicado**: si el F1-macro no alcanza 0.60, la sección 6.1 documenta las causas probables y las decisiones para las fases siguientes.

In [21]:
from ml.train.baseline import train_one_model, tune_baseline

results = {}
for kind in ('rf', 'xgb'):
    if TUNE:
        best_params = tune_baseline(df, model=kind)
        results[kind] = train_one_model(
            df, model=kind, hyperparams=best_params
        )
    else:
        results[kind] = train_one_model(df, model=kind)
    print(f'{kind.upper()}  entrenado.')

2026-05-26 20:10:55 [info     ] spatial_folds_cache_hit        n_folds=5 path=data\test_fixtures\baseline_spatial_folds_n85951_k5_b1_s42.parquet

2026-05-26 20:10:55 [info     ] baseline_tuning_start          model=rf n_combos=8 n_fits=40 n_folds=5 search_n_jobs=-1

Fitting 5 folds for each of 8 candidates, totalling 40 fits

2026-05-26 20:18:13 [info     ] baseline_tuned                 best_params={'max_depth': 15, 'min_samples_leaf': 10, 'n_estimators': 150} best_score=0.30156642961559227 model=rf n_combos=8

2026-05-26 20:18:13 [info     ] spatial_folds_cache_hit        n_folds=5 path=data\test_fixtures\baseline_spatial_folds_n85951_k5_b1_s42.parquet

2026-05-26 20:18:13 [info     ] spatial_cv_start               n_classes=18 n_folds=5

2026-05-26 20:18:13 [info     ] spatial_cv_fold_start          fold=1/5 n_test=23157 n_train=62794

2026-05-26 20:18:14 [info     ] scaler_persisted               n_features=185 n_train=62794 path=C:\Users\arthu\AppData\Local\Temp\tmpgwx6usei\fold_0_scaler.joblib version=v1

2026-05-26 20:20:00 [info     ] spatial_cv_fold_done           f1_macro=0.3037 fold=1/5

2026-05-26 20:20:00 [info     ] spatial_cv_fold_start          fold=2/5 n_test=8470 n_train=77481

2026-05-26 20:20:00 [info     ] scaler_persisted               n_features=185 n_train=77481 path=C:\Users\arthu\AppData\Local\Temp\tmpkcnyz5_5\fold_1_scaler.joblib version=v1

2026-05-26 20:22:12 [info     ] spatial_cv_fold_done           f1_macro=0.2521 fold=2/5

2026-05-26 20:22:12 [info     ] spatial_cv_fold_start          fold=3/5 n_test=22838 n_train=63113

2026-05-26 20:22:12 [info     ] scaler_persisted               n_features=185 n_train=63113 path=C:\Users\arthu\AppData\Local\Temp\tmpu42qil1n\fold_2_scaler.joblib version=v1

2026-05-26 20:23:59 [info     ] spatial_cv_fold_done           f1_macro=0.2916 fold=3/5

2026-05-26 20:23:59 [info     ] spatial_cv_fold_start          fold=4/5 n_test=20801 n_train=65150

2026-05-26 20:23:59 [info     ] scaler_persisted               n_features=185 n_train=65150 path=C:\Users\arthu\AppData\Local\Temp\tmpww5ekrlc\fold_3_scaler.joblib version=v1

2026-05-26 20:25:49 [info     ] spatial_cv_fold_done           f1_macro=0.1666 fold=4/5

2026-05-26 20:25:49 [info     ] spatial_cv_fold_start          fold=5/5 n_test=10685 n_train=75266

2026-05-26 20:25:50 [info     ] scaler_persisted               n_features=185 n_train=75266 path=C:\Users\arthu\AppData\Local\Temp\tmparf6g8jw\fold_4_scaler.joblib version=v1

2026-05-26 20:27:51 [info     ] spatial_cv_fold_done           f1_macro=0.2048 fold=5/5

2026-05-26 20:30:10 [info     ] baseline_trained               f1_macro_oof=0.2998512195816775 model=rf n_classes=18 n_features=185 n_samples=85951

RF  entrenado.

2026-05-26 20:30:11 [info     ] spatial_folds_cache_hit        n_folds=5 path=data\test_fixtures\baseline_spatial_folds_n85951_k5_b1_s42.parquet

2026-05-26 20:30:11 [info     ] xgb_device_resolved            device=cuda gpu='NVIDIA GeForce RTX 4070 Laptop GPU'

2026-05-26 20:30:11 [info     ] xgb_device_resolved            device=cuda gpu='NVIDIA GeForce RTX 4070 Laptop GPU'

2026-05-26 20:30:11 [info     ] baseline_tuning_start          model=xgb n_combos=8 n_fits=40 n_folds=5 search_n_jobs=1

Fitting 5 folds for each of 8 candidates, totalling 40 fits

[CV] END ..learning_rate=0.05, max_depth=6, n_estimators=300; total time=  29.4s

[CV] END ..learning_rate=0.05, max_depth=6, n_estimators=300; total time=  31.2s

[CV] END ..learning_rate=0.05, max_depth=6, n_estimators=300; total time=  29.7s

[CV] END ..learning_rate=0.05, max_depth=6, n_estimators=300; total time=  30.9s

[CV] END ..learning_rate=0.05, max_depth=6, n_estimators=300; total time=  32.4s

[CV] END ..learning_rate=0.05, max_depth=6, n_estimators=400; total time=  39.1s

[CV] END ..learning_rate=0.05, max_depth=6, n_estimators=400; total time=  40.6s

[CV] END ..learning_rate=0.05, max_depth=6, n_estimators=400; total time=  38.8s

[CV] END ..learning_rate=0.05, max_depth=6, n_estimators=400; total time=  39.0s

[CV] END ..learning_rate=0.05, max_depth=6, n_estimators=400; total time=  40.8s

[CV] END ..learning_rate=0.05, max_depth=8, n_estimators=300; total time=  59.2s

[CV] END ..learning_rate=0.05, max_depth=8, n_estimators=300; total time= 1.0min

[CV] END ..learning_rate=0.05, max_depth=8, n_estimators=300; total time=  59.6s

[CV] END ..learning_rate=0.05, max_depth=8, n_estimators=300; total time=  56.5s

[CV] END ..learning_rate=0.05, max_depth=8, n_estimators=300; total time= 1.0min

[CV] END ..learning_rate=0.05, max_depth=8, n_estimators=400; total time= 1.3min

[CV] END ..learning_rate=0.05, max_depth=8, n_estimators=400; total time= 1.3min

[CV] END ..learning_rate=0.05, max_depth=8, n_estimators=400; total time= 1.3min

[CV] END ..learning_rate=0.05, max_depth=8, n_estimators=400; total time= 1.3min

[CV] END ..learning_rate=0.05, max_depth=8, n_estimators=400; total time= 1.4min

[CV] END ...learning_rate=0.1, max_depth=6, n_estimators=300; total time=  28.7s

[CV] END ...learning_rate=0.1, max_depth=6, n_estimators=300; total time=  30.1s

[CV] END ...learning_rate=0.1, max_depth=6, n_estimators=300; total time=  28.9s

[CV] END ...learning_rate=0.1, max_depth=6, n_estimators=300; total time=  29.0s

[CV] END ...learning_rate=0.1, max_depth=6, n_estimators=300; total time=  30.1s

[CV] END ...learning_rate=0.1, max_depth=6, n_estimators=400; total time=  37.6s

[CV] END ...learning_rate=0.1, max_depth=6, n_estimators=400; total time=  40.1s

[CV] END ...learning_rate=0.1, max_depth=6, n_estimators=400; total time=  37.3s

[CV] END ...learning_rate=0.1, max_depth=6, n_estimators=400; total time=  37.2s

[CV] END ...learning_rate=0.1, max_depth=6, n_estimators=400; total time=  40.0s

[CV] END ...learning_rate=0.1, max_depth=8, n_estimators=300; total time=  53.5s

[CV] END ...learning_rate=0.1, max_depth=8, n_estimators=300; total time=  57.0s

[CV] END ...learning_rate=0.1, max_depth=8, n_estimators=300; total time=  53.6s

[CV] END ...learning_rate=0.1, max_depth=8, n_estimators=300; total time=  45.8s

[CV] END ...learning_rate=0.1, max_depth=8, n_estimators=300; total time=  57.1s

[CV] END ...learning_rate=0.1, max_depth=8, n_estimators=400; total time= 1.1min

[CV] END ...learning_rate=0.1, max_depth=8, n_estimators=400; total time= 1.2min

[CV] END ...learning_rate=0.1, max_depth=8, n_estimators=400; total time= 1.1min

[CV] END ...learning_rate=0.1, max_depth=8, n_estimators=400; total time=  56.5s

[CV] END ...learning_rate=0.1, max_depth=8, n_estimators=400; total time= 1.2min

2026-05-26 21:04:39 [info     ] baseline_tuned                 best_params={'learning_rate': 0.1, 'max_depth': 8, 'n_estimators': 400} best_score=0.3333915516183149 model=xgb n_combos=8

2026-05-26 21:04:39 [info     ] spatial_folds_cache_hit        n_folds=5 path=data\test_fixtures\baseline_spatial_folds_n85951_k5_b1_s42.parquet

2026-05-26 21:04:39 [info     ] spatial_cv_start               n_classes=18 n_folds=5

2026-05-26 21:04:39 [info     ] spatial_cv_fold_start          fold=1/5 n_test=23157 n_train=62794

2026-05-26 21:04:39 [info     ] scaler_persisted               n_features=185 n_train=62794 path=C:\Users\arthu\AppData\Local\Temp\tmpf52kvnbh\fold_0_scaler.joblib version=v1

2026-05-26 21:04:40 [info     ] xgb_device_resolved            device=cuda gpu='NVIDIA GeForce RTX 4070 Laptop GPU'

2026-05-26 21:05:48 [info     ] spatial_cv_fold_done           f1_macro=0.4425 fold=1/5

2026-05-26 21:05:48 [info     ] spatial_cv_fold_start          fold=2/5 n_test=8470 n_train=77481

2026-05-26 21:05:49 [info     ] scaler_persisted               n_features=185 n_train=77481 path=C:\Users\arthu\AppData\Local\Temp\tmpvwr5zo2_\fold_1_scaler.joblib version=v1

2026-05-26 21:05:49 [info     ] xgb_device_resolved            device=cuda gpu='NVIDIA GeForce RTX 4070 Laptop GPU'

2026-05-26 21:07:03 [info     ] spatial_cv_fold_done           f1_macro=0.3752 fold=2/5

2026-05-26 21:07:03 [info     ] spatial_cv_fold_start          fold=3/5 n_test=22838 n_train=63113

2026-05-26 21:07:03 [info     ] scaler_persisted               n_features=185 n_train=63113 path=C:\Users\arthu\AppData\Local\Temp\tmpkoi2s0u0\fold_2_scaler.joblib version=v1

2026-05-26 21:07:04 [info     ] xgb_device_resolved            device=cuda gpu='NVIDIA GeForce RTX 4070 Laptop GPU'

2026-05-26 21:08:11 [info     ] spatial_cv_fold_done           f1_macro=0.4039 fold=3/5

2026-05-26 21:08:11 [info     ] spatial_cv_fold_start          fold=4/5 n_test=20801 n_train=65150

2026-05-26 21:08:11 [info     ] scaler_persisted               n_features=185 n_train=65150 path=C:\Users\arthu\AppData\Local\Temp\tmp0cnroh24\fold_3_scaler.joblib version=v1

2026-05-26 21:08:12 [info     ] xgb_device_resolved            device=cuda gpu='NVIDIA GeForce RTX 4070 Laptop GPU'

2026-05-26 21:09:15 [info     ] spatial_cv_fold_done           f1_macro=0.1986 fold=4/5

2026-05-26 21:09:15 [info     ] spatial_cv_fold_start          fold=5/5 n_test=10685 n_train=75266

2026-05-26 21:09:15 [info     ] scaler_persisted               n_features=185 n_train=75266 path=C:\Users\arthu\AppData\Local\Temp\tmp_wnxvap5\fold_4_scaler.joblib version=v1

2026-05-26 21:09:15 [info     ] xgb_device_resolved            device=cuda gpu='NVIDIA GeForce RTX 4070 Laptop GPU'

2026-05-26 21:10:29 [info     ] spatial_cv_fold_done           f1_macro=0.314 fold=5/5

2026-05-26 21:10:29 [info     ] xgb_device_resolved            device=cuda gpu='NVIDIA GeForce RTX 4070 Laptop GPU'

2026-05-26 21:11:46 [info     ] baseline_trained               f1_macro_oof=0.40545164149630053 model=xgb n_classes=18 n_features=185 n_samples=85951

XGB  entrenado.

In [22]:
# Tabla resumen de las metricas CV-mean por modelo.
summary = pl.DataFrame(
    [
        {
            'modelo': kind.upper(),
            **{m: round(v, 4) for m, v in res.metrics.items()},
        }
        for kind, res in results.items()
    ]
)
summary

shape: (2, 6)
┌────────┬──────────┬─────────────┬────────┬──────────┬─────────────┐
│ modelo ┆ f1_macro ┆ f1_weighted ┆ miou   ┆ accuracy ┆ cohen_kappa │
│ ---    ┆ ---      ┆ ---         ┆ ---    ┆ ---      ┆ ---         │
│ str    ┆ f64      ┆ f64         ┆ f64    ┆ f64      ┆ f64         │
╞════════╪══════════╪═════════════╪════════╪══════════╪═════════════╡
│ RF     ┆ 0.2999   ┆ 0.6358      ┆ 0.228  ┆ 0.6998   ┆ 0.6141      │
│ XGB    ┆ 0.4055   ┆ 0.6894      ┆ 0.3085 ┆ 0.7238   ┆ 0.6512      │
└────────┴──────────┴─────────────┴────────┴──────────┴─────────────┘

In [23]:
# Veredicto frente al umbral de referencia.
best_kind = max(results, key=lambda k: results[k].metrics['f1_macro'])
best_f1 = results[best_kind].metrics['f1_macro']
passed = best_f1 >= F1_THRESHOLD
print(f'Mejor modelo: {best_kind.upper()}  |  F1-macro = {best_f1:.4f}')
print(f'Umbral de referencia: {F1_THRESHOLD:.2f}  |  '
      f'{"alcanzado" if passed else "no alcanzado — ver 6.1"}')

Mejor modelo: XGB  |  F1-macro = 0.4055
Umbral de referencia: 0.60  |  no alcanzado — ver 6.1

### 6.1 Causas probables y decisiones para las fases siguientes

Si el F1-macro promedio queda por debajo de 0.60, las causas probables son:

1. **Gran cantidad de clases (20 tipos de cultivo).** Varios cultivos son espectralmente parecidos; un modelo de árboles sobre un resumen anual no capta la firma estacional que los distingue.
2. **Clases desbalanceadas.** Pese al balanceo aplicado, las clases minoritarias aportan pocas parcelas y el F1-macro las penaliza con fuerza.
3. **Límite de un modelo de árboles sobre un resumen anual.** El embedding AlphaEarth condensa el año en 64 dimensiones y pierde la dinámica intra-anual que un modelo de series temporales sí aprovecha.

Decisiones concretas para las fases siguientes:

- Modelos que explotan la **serie temporal completa** de Sentinel-2 (no el resumen anual), capaces de captar la estacionalidad que separa cultivos parecidos.
- **Combinar varios modelos** (de árboles, temporales y de lenguaje-visión) para recuperar señal complementaria que ningún modelo aislado captura.

## 7. Comparativa AlphaEarth vs Sentinel-2 crudo

Esta sección compara el baseline sobre **tres vistas distintas de las mismas parcelas**, para responder con evidencia una pregunta central: ¿el embedding AlphaEarth aporta valor frente a las bandas Sentinel-2 sin procesar?

| Escenario | Características | Origen |
|-----------|-----------------|--------|
| **(a) AlphaEarth** | 64 dimensiones | embedding AlphaEarth Foundations |
| **(b) Sentinel-2 crudo** | 10 bandas promedio | bandas Sentinel-2 sin procesar, agregadas por parcela |
| **(c) Vector combinado** | 187 características | ingeniería de características espectro-temporales |

Metodología de la comparativa:

- Los 3 escenarios se cruzan por parcela para evaluarse sobre **exactamente el mismo conjunto de parcelas**, no sobre tres muestras distintas.
- Se reutiliza la **misma validación cruzada espacial** para los 3 escenarios; así la diferencia de F1-macro refleja la calidad de las características, no el azar de la partición.
- Se reporta también el **tiempo de entrenamiento** de cada modelo.

Si el escenario (b) Sentinel-2 crudo aún no se ha generado, esta sección degrada de forma controlada y documenta la ausencia sin interrumpir el notebook.

In [24]:
from pathlib import Path

from ml.eval.comparison import (
    build_comparison_table,
    export_comparison_latex,
)

scenario_paths = {
    'alphaearth': SCENARIO_ALPHAEARTH_PATH,
    's2_raw': SCENARIO_S2_RAW_PATH,
    'combined': SCENARIO_COMBINED_PATH,
}
missing = {
    key: path
    for key, path in scenario_paths.items()
    if not Path(path).exists()
}
comparison_available = not missing
if missing:
    print('Escenarios no disponibles -> comparativa omitida:')
    for key, path in missing.items():
        print(f'  - {key}: {path}')
    print('Genera el escenario (b) con `make s2-raw-parcels`.')
else:
    print('Los 3 escenarios estan disponibles para la comparativa.')

Los 3 escenarios estan disponibles para la comparativa.

In [25]:
# Comparativa de los 3 escenarios (6 filas = 3 escenarios x 2 modelos).
comparison_result = None
if comparison_available:
    comparison_result = build_comparison_table(
        scenario_paths,
        k_folds=COMPARISON_K_FOLDS,
        max_samples=COMPARISON_MAX_SAMPLES,
        random_state=42,
    )
    print(f'Parcelas en el inner join: '
          f'{comparison_result.n_parcels:,}')
    comparison_result.table
else:
    print('Comparativa omitida — ver celda anterior.')

2026-05-26 21:11:47 [info     ] scenarios_aligned              n_common=85951 scenarios=['alphaearth', 'combined', 's2_raw']

2026-05-26 21:11:47 [info     ] comparison_table_start         k_folds=5 n_effective=85951 n_parcels=85951

2026-05-26 21:11:47 [info     ] spatial_folds_cache_hit        n_folds=5 path=data\test_fixtures\baseline_spatial_folds_n85951_k5_b1_s42.parquet

2026-05-26 21:11:47 [info     ] spatial_cv_start               n_classes=18 n_folds=5

2026-05-26 21:11:47 [info     ] spatial_cv_fold_start          fold=1/5 n_test=23157 n_train=62794

2026-05-26 21:11:47 [info     ] scaler_persisted               n_features=65 n_train=62794 path=C:\Users\arthu\AppData\Local\Temp\tmp_83l6e92\fold_0_scaler.joblib version=v1

2026-05-26 21:11:55 [info     ] spatial_cv_fold_done           f1_macro=0.2971 fold=1/5

2026-05-26 21:11:55 [info     ] spatial_cv_fold_start          fold=2/5 n_test=8470 n_train=77481

2026-05-26 21:11:56 [info     ] scaler_persisted               n_features=65 n_train=77481 path=C:\Users\arthu\AppData\Local\Temp\tmpq889cwxh\fold_1_scaler.joblib version=v1

2026-05-26 21:12:06 [info     ] spatial_cv_fold_done           f1_macro=0.2848 fold=2/5

2026-05-26 21:12:06 [info     ] spatial_cv_fold_start          fold=3/5 n_test=22838 n_train=63113

2026-05-26 21:12:06 [info     ] scaler_persisted               n_features=65 n_train=63113 path=C:\Users\arthu\AppData\Local\Temp\tmpwldp2qiu\fold_2_scaler.joblib version=v1

2026-05-26 21:12:14 [info     ] spatial_cv_fold_done           f1_macro=0.3932 fold=3/5

2026-05-26 21:12:14 [info     ] spatial_cv_fold_start          fold=4/5 n_test=20801 n_train=65150

2026-05-26 21:12:14 [info     ] scaler_persisted               n_features=65 n_train=65150 path=C:\Users\arthu\AppData\Local\Temp\tmp8odnewo6\fold_3_scaler.joblib version=v1

2026-05-26 21:12:22 [info     ] spatial_cv_fold_done           f1_macro=0.1894 fold=4/5

2026-05-26 21:12:22 [info     ] spatial_cv_fold_start          fold=5/5 n_test=10685 n_train=75266

2026-05-26 21:12:22 [info     ] scaler_persisted               n_features=65 n_train=75266 path=C:\Users\arthu\AppData\Local\Temp\tmpfebevn5s\fold_4_scaler.joblib version=v1

2026-05-26 21:12:33 [info     ] spatial_cv_fold_done           f1_macro=0.2453 fold=5/5

2026-05-26 21:12:44 [info     ] baseline_trained               f1_macro_oof=0.3274787234982039 model=rf n_classes=18 n_features=65 n_samples=85951

2026-05-26 21:12:44 [info     ] comparison_cell_done           f1_macro=0.3275 model=rf scenario=alphaearth train_time_s=56.82

2026-05-26 21:12:44 [info     ] spatial_folds_cache_hit        n_folds=5 path=data\test_fixtures\baseline_spatial_folds_n85951_k5_b1_s42.parquet

2026-05-26 21:12:44 [info     ] spatial_cv_start               n_classes=18 n_folds=5

2026-05-26 21:12:44 [info     ] spatial_cv_fold_start          fold=1/5 n_test=23157 n_train=62794

2026-05-26 21:12:44 [info     ] scaler_persisted               n_features=65 n_train=62794 path=C:\Users\arthu\AppData\Local\Temp\tmpx3wt4052\fold_0_scaler.joblib version=v1

2026-05-26 21:12:44 [info     ] xgb_device_resolved            device=cuda gpu='NVIDIA GeForce RTX 4070 Laptop GPU'

2026-05-26 21:13:27 [info     ] spatial_cv_fold_done           f1_macro=0.3341 fold=1/5

2026-05-26 21:13:27 [info     ] spatial_cv_fold_start          fold=2/5 n_test=8470 n_train=77481

2026-05-26 21:13:27 [info     ] scaler_persisted               n_features=65 n_train=77481 path=C:\Users\arthu\AppData\Local\Temp\tmp9u6btg1f\fold_1_scaler.joblib version=v1

2026-05-26 21:13:28 [info     ] xgb_device_resolved            device=cuda gpu='NVIDIA GeForce RTX 4070 Laptop GPU'

2026-05-26 21:14:12 [info     ] spatial_cv_fold_done           f1_macro=0.3214 fold=2/5

2026-05-26 21:14:12 [info     ] spatial_cv_fold_start          fold=3/5 n_test=22838 n_train=63113

2026-05-26 21:14:12 [info     ] scaler_persisted               n_features=65 n_train=63113 path=C:\Users\arthu\AppData\Local\Temp\tmpaylo71cb\fold_2_scaler.joblib version=v1

2026-05-26 21:14:13 [info     ] xgb_device_resolved            device=cuda gpu='NVIDIA GeForce RTX 4070 Laptop GPU'

2026-05-26 21:14:58 [info     ] spatial_cv_fold_done           f1_macro=0.4102 fold=3/5

2026-05-26 21:14:58 [info     ] spatial_cv_fold_start          fold=4/5 n_test=20801 n_train=65150

2026-05-26 21:14:58 [info     ] scaler_persisted               n_features=65 n_train=65150 path=C:\Users\arthu\AppData\Local\Temp\tmp5cp_pewe\fold_3_scaler.joblib version=v1

2026-05-26 21:14:58 [info     ] xgb_device_resolved            device=cuda gpu='NVIDIA GeForce RTX 4070 Laptop GPU'

2026-05-26 21:15:42 [info     ] spatial_cv_fold_done           f1_macro=0.2056 fold=4/5

2026-05-26 21:15:42 [info     ] spatial_cv_fold_start          fold=5/5 n_test=10685 n_train=75266

2026-05-26 21:15:43 [info     ] scaler_persisted               n_features=65 n_train=75266 path=C:\Users\arthu\AppData\Local\Temp\tmpudkzso25\fold_4_scaler.joblib version=v1

2026-05-26 21:15:43 [info     ] xgb_device_resolved            device=cuda gpu='NVIDIA GeForce RTX 4070 Laptop GPU'

2026-05-26 21:16:31 [info     ] spatial_cv_fold_done           f1_macro=0.2785 fold=5/5

2026-05-26 21:16:31 [info     ] xgb_device_resolved            device=cuda gpu='NVIDIA GeForce RTX 4070 Laptop GPU'

2026-05-26 21:17:19 [info     ] baseline_trained               f1_macro_oof=0.3523201817548541 model=xgb n_classes=18 n_features=65 n_samples=85951

2026-05-26 21:17:19 [info     ] comparison_cell_done           f1_macro=0.3523 model=xgb scenario=alphaearth train_time_s=275.11

2026-05-26 21:17:19 [info     ] spatial_folds_cache_hit        n_folds=5 path=data\test_fixtures\baseline_spatial_folds_n85951_k5_b1_s42.parquet

2026-05-26 21:17:19 [info     ] spatial_cv_start               n_classes=18 n_folds=5

2026-05-26 21:17:19 [info     ] spatial_cv_fold_start          fold=1/5 n_test=23157 n_train=62794

2026-05-26 21:17:19 [info     ] scaler_persisted               n_features=10 n_train=62794 path=C:\Users\arthu\AppData\Local\Temp\tmp0bjaz1fo\fold_0_scaler.joblib version=v1

2026-05-26 21:17:22 [info     ] spatial_cv_fold_done           f1_macro=0.1938 fold=1/5

2026-05-26 21:17:22 [info     ] spatial_cv_fold_start          fold=2/5 n_test=8470 n_train=77481

2026-05-26 21:17:22 [info     ] scaler_persisted               n_features=10 n_train=77481 path=C:\Users\arthu\AppData\Local\Temp\tmpr6l_85k4\fold_1_scaler.joblib version=v1

2026-05-26 21:17:26 [info     ] spatial_cv_fold_done           f1_macro=0.2193 fold=2/5

2026-05-26 21:17:26 [info     ] spatial_cv_fold_start          fold=3/5 n_test=22838 n_train=63113

2026-05-26 21:17:26 [info     ] scaler_persisted               n_features=10 n_train=63113 path=C:\Users\arthu\AppData\Local\Temp\tmpcj7_qzaz\fold_2_scaler.joblib version=v1

2026-05-26 21:17:29 [info     ] spatial_cv_fold_done           f1_macro=0.1815 fold=3/5

2026-05-26 21:17:29 [info     ] spatial_cv_fold_start          fold=4/5 n_test=20801 n_train=65150

2026-05-26 21:17:29 [info     ] scaler_persisted               n_features=10 n_train=65150 path=C:\Users\arthu\AppData\Local\Temp\tmpbbnso38t\fold_3_scaler.joblib version=v1

2026-05-26 21:17:33 [info     ] spatial_cv_fold_done           f1_macro=0.0721 fold=4/5

2026-05-26 21:17:33 [info     ] spatial_cv_fold_start          fold=5/5 n_test=10685 n_train=75266

2026-05-26 21:17:33 [info     ] scaler_persisted               n_features=10 n_train=75266 path=C:\Users\arthu\AppData\Local\Temp\tmp06iojfyf\fold_4_scaler.joblib version=v1

2026-05-26 21:17:36 [info     ] spatial_cv_fold_done           f1_macro=0.1622 fold=5/5

2026-05-26 21:17:40 [info     ] baseline_trained               f1_macro_oof=0.20443930308405847 model=rf n_classes=18 n_features=10 n_samples=85951

2026-05-26 21:17:40 [info     ] comparison_cell_done           f1_macro=0.2044 model=rf scenario=s2_raw train_time_s=21.27

2026-05-26 21:17:40 [info     ] spatial_folds_cache_hit        n_folds=5 path=data\test_fixtures\baseline_spatial_folds_n85951_k5_b1_s42.parquet

2026-05-26 21:17:40 [info     ] spatial_cv_start               n_classes=18 n_folds=5

2026-05-26 21:17:40 [info     ] spatial_cv_fold_start          fold=1/5 n_test=23157 n_train=62794

2026-05-26 21:17:40 [info     ] scaler_persisted               n_features=10 n_train=62794 path=C:\Users\arthu\AppData\Local\Temp\tmp7vwez557\fold_0_scaler.joblib version=v1

2026-05-26 21:17:41 [info     ] xgb_device_resolved            device=cuda gpu='NVIDIA GeForce RTX 4070 Laptop GPU'

2026-05-26 21:18:10 [info     ] spatial_cv_fold_done           f1_macro=0.2533 fold=1/5

2026-05-26 21:18:10 [info     ] spatial_cv_fold_start          fold=2/5 n_test=8470 n_train=77481

2026-05-26 21:18:10 [info     ] scaler_persisted               n_features=10 n_train=77481 path=C:\Users\arthu\AppData\Local\Temp\tmp7puvh3kf\fold_1_scaler.joblib version=v1

2026-05-26 21:18:10 [info     ] xgb_device_resolved            device=cuda gpu='NVIDIA GeForce RTX 4070 Laptop GPU'

2026-05-26 21:18:41 [info     ] spatial_cv_fold_done           f1_macro=0.2474 fold=2/5

2026-05-26 21:18:41 [info     ] spatial_cv_fold_start          fold=3/5 n_test=22838 n_train=63113

2026-05-26 21:18:41 [info     ] scaler_persisted               n_features=10 n_train=63113 path=C:\Users\arthu\AppData\Local\Temp\tmpnhxdd_gj\fold_2_scaler.joblib version=v1

2026-05-26 21:18:41 [info     ] xgb_device_resolved            device=cuda gpu='NVIDIA GeForce RTX 4070 Laptop GPU'

2026-05-26 21:19:10 [info     ] spatial_cv_fold_done           f1_macro=0.2459 fold=3/5

2026-05-26 21:19:10 [info     ] spatial_cv_fold_start          fold=4/5 n_test=20801 n_train=65150

2026-05-26 21:19:10 [info     ] scaler_persisted               n_features=10 n_train=65150 path=C:\Users\arthu\AppData\Local\Temp\tmpwfc6v_dd\fold_3_scaler.joblib version=v1

2026-05-26 21:19:10 [info     ] xgb_device_resolved            device=cuda gpu='NVIDIA GeForce RTX 4070 Laptop GPU'

2026-05-26 21:19:39 [info     ] spatial_cv_fold_done           f1_macro=0.0947 fold=4/5

2026-05-26 21:19:39 [info     ] spatial_cv_fold_start          fold=5/5 n_test=10685 n_train=75266

2026-05-26 21:19:39 [info     ] scaler_persisted               n_features=10 n_train=75266 path=C:\Users\arthu\AppData\Local\Temp\tmpwlb2y9yw\fold_4_scaler.joblib version=v1

2026-05-26 21:19:39 [info     ] xgb_device_resolved            device=cuda gpu='NVIDIA GeForce RTX 4070 Laptop GPU'

2026-05-26 21:20:11 [info     ] spatial_cv_fold_done           f1_macro=0.2077 fold=5/5

2026-05-26 21:20:11 [info     ] xgb_device_resolved            device=cuda gpu='NVIDIA GeForce RTX 4070 Laptop GPU'

2026-05-26 21:20:42 [info     ] baseline_trained               f1_macro_oof=0.257016489376915 model=xgb n_classes=18 n_features=10 n_samples=85951

2026-05-26 21:20:42 [info     ] comparison_cell_done           f1_macro=0.257 model=xgb scenario=s2_raw train_time_s=181.73

2026-05-26 21:20:42 [info     ] spatial_folds_cache_hit        n_folds=5 path=data\test_fixtures\baseline_spatial_folds_n85951_k5_b1_s42.parquet

2026-05-26 21:20:42 [info     ] spatial_cv_start               n_classes=18 n_folds=5

2026-05-26 21:20:42 [info     ] spatial_cv_fold_start          fold=1/5 n_test=23157 n_train=62794

2026-05-26 21:20:43 [info     ] scaler_persisted               n_features=185 n_train=62794 path=C:\Users\arthu\AppData\Local\Temp\tmpepev9ik6\fold_0_scaler.joblib version=v1

2026-05-26 21:20:54 [info     ] spatial_cv_fold_done           f1_macro=0.3824 fold=1/5

2026-05-26 21:20:54 [info     ] spatial_cv_fold_start          fold=2/5 n_test=8470 n_train=77481

2026-05-26 21:20:54 [info     ] scaler_persisted               n_features=185 n_train=77481 path=C:\Users\arthu\AppData\Local\Temp\tmpyo5punjd\fold_1_scaler.joblib version=v1

2026-05-26 21:21:10 [info     ] spatial_cv_fold_done           f1_macro=0.3368 fold=2/5

2026-05-26 21:21:10 [info     ] spatial_cv_fold_start          fold=3/5 n_test=22838 n_train=63113

2026-05-26 21:21:10 [info     ] scaler_persisted               n_features=185 n_train=63113 path=C:\Users\arthu\AppData\Local\Temp\tmpl0gd9ftm\fold_2_scaler.joblib version=v1

2026-05-26 21:21:22 [info     ] spatial_cv_fold_done           f1_macro=0.3511 fold=3/5

2026-05-26 21:21:22 [info     ] spatial_cv_fold_start          fold=4/5 n_test=20801 n_train=65150

2026-05-26 21:21:22 [info     ] scaler_persisted               n_features=185 n_train=65150 path=C:\Users\arthu\AppData\Local\Temp\tmp_sagzgf5\fold_3_scaler.joblib version=v1

2026-05-26 21:21:35 [info     ] spatial_cv_fold_done           f1_macro=0.1721 fold=4/5

2026-05-26 21:21:35 [info     ] spatial_cv_fold_start          fold=5/5 n_test=10685 n_train=75266

2026-05-26 21:21:35 [info     ] scaler_persisted               n_features=185 n_train=75266 path=C:\Users\arthu\AppData\Local\Temp\tmp57n13lut\fold_4_scaler.joblib version=v1

2026-05-26 21:21:50 [info     ] spatial_cv_fold_done           f1_macro=0.2611 fold=5/5

2026-05-26 21:22:06 [info     ] baseline_trained               f1_macro_oof=0.364621305028934 model=rf n_classes=18 n_features=185 n_samples=85951

2026-05-26 21:22:06 [info     ] comparison_cell_done           f1_macro=0.3646 model=rf scenario=combined train_time_s=83.87

2026-05-26 21:22:06 [info     ] spatial_folds_cache_hit        n_folds=5 path=data\test_fixtures\baseline_spatial_folds_n85951_k5_b1_s42.parquet

2026-05-26 21:22:06 [info     ] spatial_cv_start               n_classes=18 n_folds=5

2026-05-26 21:22:06 [info     ] spatial_cv_fold_start          fold=1/5 n_test=23157 n_train=62794

2026-05-26 21:22:06 [info     ] scaler_persisted               n_features=185 n_train=62794 path=C:\Users\arthu\AppData\Local\Temp\tmpkt4pyw_z\fold_0_scaler.joblib version=v1

2026-05-26 21:22:07 [info     ] xgb_device_resolved            device=cuda gpu='NVIDIA GeForce RTX 4070 Laptop GPU'

2026-05-26 21:23:21 [info     ] spatial_cv_fold_done           f1_macro=0.4515 fold=1/5

2026-05-26 21:23:21 [info     ] spatial_cv_fold_start          fold=2/5 n_test=8470 n_train=77481

2026-05-26 21:23:21 [info     ] scaler_persisted               n_features=185 n_train=77481 path=C:\Users\arthu\AppData\Local\Temp\tmp_c_87u_x\fold_1_scaler.joblib version=v1

2026-05-26 21:23:22 [info     ] xgb_device_resolved            device=cuda gpu='NVIDIA GeForce RTX 4070 Laptop GPU'

2026-05-26 21:24:47 [info     ] spatial_cv_fold_done           f1_macro=0.3786 fold=2/5

2026-05-26 21:24:47 [info     ] spatial_cv_fold_start          fold=3/5 n_test=22838 n_train=63113

2026-05-26 21:24:47 [info     ] scaler_persisted               n_features=185 n_train=63113 path=C:\Users\arthu\AppData\Local\Temp\tmpuoty327q\fold_2_scaler.joblib version=v1

2026-05-26 21:24:47 [info     ] xgb_device_resolved            device=cuda gpu='NVIDIA GeForce RTX 4070 Laptop GPU'

2026-05-26 21:26:05 [info     ] spatial_cv_fold_done           f1_macro=0.4079 fold=3/5

2026-05-26 21:26:05 [info     ] spatial_cv_fold_start          fold=4/5 n_test=20801 n_train=65150

2026-05-26 21:26:05 [info     ] scaler_persisted               n_features=185 n_train=65150 path=C:\Users\arthu\AppData\Local\Temp\tmpbrxq9xam\fold_3_scaler.joblib version=v1

2026-05-26 21:26:06 [info     ] xgb_device_resolved            device=cuda gpu='NVIDIA GeForce RTX 4070 Laptop GPU'

2026-05-26 21:27:15 [info     ] spatial_cv_fold_done           f1_macro=0.2007 fold=4/5

2026-05-26 21:27:15 [info     ] spatial_cv_fold_start          fold=5/5 n_test=10685 n_train=75266

2026-05-26 21:27:15 [info     ] scaler_persisted               n_features=185 n_train=75266 path=C:\Users\arthu\AppData\Local\Temp\tmppaksu5ed\fold_4_scaler.joblib version=v1

2026-05-26 21:27:16 [info     ] xgb_device_resolved            device=cuda gpu='NVIDIA GeForce RTX 4070 Laptop GPU'

2026-05-26 21:28:35 [info     ] spatial_cv_fold_done           f1_macro=0.3047 fold=5/5

2026-05-26 21:28:35 [info     ] xgb_device_resolved            device=cuda gpu='NVIDIA GeForce RTX 4070 Laptop GPU'

2026-05-26 21:29:55 [info     ] baseline_trained               f1_macro_oof=0.41062434664796243 model=xgb n_classes=18 n_features=185 n_samples=85951

2026-05-26 21:29:55 [info     ] comparison_cell_done           f1_macro=0.4106 model=xgb scenario=combined train_time_s=469.39

2026-05-26 21:29:55 [info     ] comparison_table_done          alphaearth_delta=0.0953 best_scenario='Vector combinado (187 feat)' n_parcels=85951

Parcelas en el inner join: 85,951

In [26]:
# Persistencia de la tabla comparativa (CSV + MD + LaTeX).
if comparison_result is not None:
    reports_dir = Path('reports/baseline')
    reports_dir.mkdir(parents=True, exist_ok=True)
    comparison_result.table.write_csv(
        reports_dir / 'comparison_alphaearth_vs_s2.csv'
    )
    md_table = (
        '# Comparativa de escenarios — baseline de cultivos\n\n'
        + comparison_result.table.to_pandas().to_markdown(index=False)
        + '\n'
    )
    (reports_dir / 'comparison_alphaearth_vs_s2.md').write_text(
        md_table, encoding='utf-8'
    )
    tex_path = export_comparison_latex(
        comparison_result, reports_dir / 'comparison_table.tex'
    )
    print(f'Tabla comparativa escrita: CSV + MD + {tex_path.name}')
else:
    print('Sin tabla comparativa que persistir.')

2026-05-26 21:29:56 [info     ] comparison_latex_written       path=reports\baseline\comparison_table.tex

Tabla comparativa escrita: CSV + MD + comparison_table.tex

In [27]:
# Barplot comparativo de F1-macro por escenario y modelo.
if comparison_result is not None:
    table = comparison_result.table
    scenarios = table['scenario'].unique(maintain_order=True).to_list()
    x = range(len(scenarios))
    width = 0.38
    fig, ax = plt.subplots(figsize=(9, 5), dpi=200)
    for offset, model in zip((-width / 2, width / 2), ('RF', 'XGB')):
        f1_by_scenario = [
            float(
                table.filter(
                    (pl.col('scenario') == sc)
                    & (pl.col('model') == model)
                )['f1_macro'][0]
            )
            for sc in scenarios
        ]
        bars = ax.bar(
            [xi + offset for xi in x], f1_by_scenario,
            width=width, label=model,
        )
        ax.bar_label(bars, fmt='%.3f', fontsize=8, padding=2)
    ax.set_xticks(list(x))
    ax.set_xticklabels(scenarios, rotation=15, ha='right', fontsize=9)
    ax.set_ylabel('F1-macro (CV espacial out-of-fold)')
    ax.set_ylim(0.0, 1.0)
    ax.set_title('Comparativa del baseline — 3 escenarios de features')
    ax.legend(title='Modelo')
    ax.grid(axis='y', alpha=0.3)
    fig.tight_layout()
    fig.savefig(
        Path('reports/baseline') / 'comparison_barplot.png',
        dpi=200, bbox_inches='tight',
    )
    plt.show()
else:
    print('Sin barplot — comparativa omitida.')

<!-- AUTO-INTERP -->
**Lectura del barplot comparativo**: las barras están agrupadas por escenario (AlphaEarth 64-dim, vector combinado, Sentinel-2 crudo) y dentro de cada grupo se compara RF vs XGB. El patrón es claro: **ambos modelos sufren la misma limitación estructural** dentro de cada escenario (RF y XGB difieren poco), pero **el escenario importa mucho** — AlphaEarth y el combinado superan al Sentinel-2 crudo por ~0.13 puntos de F1-macro. La conclusión para las fases siguientes está en la próxima sección: la palanca no es elegir mejor clasificador tabular, sino procesar la serie temporal completa (modelos U-TAE / TSViT) y no solo su resumen anual.

In [28]:
# Resumen cuantitativo del valor incremental de AlphaEarth.
if comparison_result is not None:
    delta = comparison_result.alphaearth_delta
    print(f'Escenario ganador: {comparison_result.best_scenario}')
    print(f'Delta F1-macro AlphaEarth - Sentinel-2 crudo: '
          f'{delta:+.4f}')
    if delta > 0.0:
        print('-> El embedding AlphaEarth aporta valor incremental '
              'sobre las bandas crudas.')
    else:
        print('-> El embedding AlphaEarth NO supera a las bandas '
              'crudas en este baseline tabular.')
else:
    print('Sin delta — comparativa omitida.')

Escenario ganador: Vector combinado (187 feat)
Delta F1-macro AlphaEarth - Sentinel-2 crudo: +0.0953
-> El embedding AlphaEarth aporta valor incremental sobre las bandas crudas.

## 8. Conclusiones

Este notebook construyó un punto de referencia para clasificar cultivos a partir de imágenes satelitales y lo sometió a tres preguntas: ¿qué tan bien funciona un modelo de árboles sencillo?, ¿qué características explican sus predicciones?, y ¿el embedding AlphaEarth aporta algo frente a las bandas satelitales sin procesar? Lo que encontramos:

### ¿AlphaEarth aporta valor?

La comparativa de la sección 7 da una respuesta con datos. El **embedding AlphaEarth** es una representación compacta de 64 números que resume un año de observaciones satelitales; las **bandas Sentinel-2 crudas** son los 10 canales del satélite promediados. La diferencia de F1-macro entre ambos escenarios indica si ese resumen aprendido aporta información que el promedio simple de las bandas pierde.

- Si AlphaEarth supera a las bandas crudas, el resumen aprendido captura señal multisensor y estacional que el promedio destruye.
- Si quedan empatados, ambas representaciones son equivalentes para un modelo de árboles a nivel de parcela.
- Si las bandas crudas ganan, el problema no está en la representación sino en haber promediado el tiempo: la solución es usar la serie temporal completa.

### Hallazgos

1. **El techo de este modelo es estructural, no de ajuste.** Las curvas de aprendizaje (sección 5b) muestran que el modelo no sobreajusta: simplemente ha llegado a su capacidad máxima sobre datos que ya perdieron la dimensión temporal. Añadir más árboles o más profundidad no moverá ese techo.
2. **La representación de los datos importa más que el algoritmo.** Random Forest y XGBoost rinden parecido dentro de cada escenario; la diferencia grande de desempeño aparece **entre escenarios**. La pregunta clave no es qué clasificador usar, sino cómo representar la evolución del cultivo en el tiempo.
3. **Promediar el tiempo es el cuello de botella.** Los tres escenarios resumen el año en un solo vector. Pero cultivos espectralmente parecidos solo se distinguen por **cómo cambian a lo largo de la temporada** — y esa trayectoria se pierde al promediar.

### Lo que sigue

- **Modelos que usen la serie temporal completa.** Este baseline fija el piso de desempeño; los modelos siguientes deben procesar la secuencia de imágenes Sentinel-2 mes a mes — no su promedio anual — para captar la estacionalidad que separa cultivos parecidos. Si aún así no superan estas cifras, el límite estaría en los datos, no en el modelo.
- **AlphaEarth como característica de apoyo.** El embedding se incorporará como una entrada más al combinar varios modelos, no como sustituto de la serie temporal cruda.
- **Mismo protocolo de evaluación.** La validación cruzada espacial con zona de exclusión entre parcelas vecinas se mantiene en las fases siguientes, para que las cifras sean comparables entre experimentos.

El baseline cumple su propósito: es **honesto, interpretable y reproducible** — establece el piso de desempeño, documenta sus propias limitaciones y deja un protocolo de evaluación y una métrica principal que el resto del proyecto puede heredar.